FROM mcr.microsoft.com/dotnet/aspnet:5.0
COPY /bin/Release/netcoreapp5.0/publish api/
WORKDIR /api
EXPOSE 5000/tcp
ENTRYPOINT dotnet Api.dll
ENV ASPNETCORE_URLS=http://+:5000
ENV COMPlus_EnableDiagnostics=0